# Generated by Django 5.1.8 on 2025-04-02 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aluno",
            old_name="fist_name_aluno",
            new_name="first_name_aluno",
        ),
        migrations.RemoveField(
            model_name="responsavel",
            name="adress",
        ),
        migrations.RemoveField(
            model_name="responsavel",
            name="fist_name",
        ),
        migrations.AddField(
            model_name="professor",
            name="first_name",
            field=models.CharField(
                default="Default_First_Name", max_length=50, verbose_name="Nome"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="responsavel",
            name="address",
            field=models.CharField(
                default="Default_Address",
                max_length=100,
                verbose_name="Endereço do responsável",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="responsavel",
            name="first_name",
            field=models.CharField(
                default="Default_First_Name",
                max_length=50,
                verbose_name="Nome do responsável",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="aluno",
            name="cpf_aluno",
            field=models.CharField(
                max_length=11, unique=True, verbose_name="CPF do aluno"
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="email_aluno",
            field=models.CharField(max_length=100, verbose_name="Email do aluno"),
        ),
        migrations.AlterField(
            model_name="professor",
            name="cpf",
            field=models.CharField(
                max_length=11, unique=True, verbose_name="CPF do professor"
            ),
        ),
        migrations.AlterField(
            model_name="responsavel",
            name="cpf",
            field=models.CharField(
                max_length=11, unique=True, verbose_name="CPF do responsável"
            ),
        ),
        migrations.AlterField(
            model_name="responsavel",
            name="email",
            field=models.CharField(max_length=100, verbose_name="Email do responsável"),
        ),
        migrations.AlterField(
            model_name="responsavel",
            name="last_name",
            field=models.CharField(
                max_length=50, verbose_name="Sobrenome do responsável"
            ),
        ),
        migrations.AlterField(
            model_name="responsavel",
            name="phone_number",
            field=models.CharField(
                max_length=15,
                verbose_name="Nº do celular (--) ---- ---- do responsável",
            ),
        ),
        migrations.CreateModel(
            name="Turma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "turma",
                    models.CharField(
                        choices=[
                            ("1A", "1º Ano A"),
                            ("1B", "1º Ano B"),
                            ("1C", "1º Ano C"),
                            ("2A", "2º Ano A"),
                            ("2B", "2º Ano B"),
                            ("2C", "2º Ano C"),
                            ("3A", "3º Ano A"),
                            ("3B", "3º Ano B"),
                            ("3C", "3º Ano C"),
                        ],
                        max_length=2,
                        verbose_name="Turma",
                    ),
                ),
                (
                    "itinerario",
                    models.CharField(
                        choices=[
                            ("DS", "Desenvolvimento de Sistemas"),
                            ("CN", "Ciências da Natureza"),
                            ("J", "Jogos"),
                        ],
                        max_length=2,
                        verbose_name="Itinerário",
                    ),
                ),
                (
                    "representante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="representante_turma",
                        to="projeto.aluno",
                        verbose_name="Representante",
                    ),
                ),
                (
                    "vice_representante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vice_representante_turma",
                        to="projeto.aluno",
                        verbose_name="Vice-Representante",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_responsavel",
                    models.EmailField(
                        max_length=254, verbose_name="Email do Responsável"
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeto.aluno",
                        verbose_name="Nome do Aluno",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeto.responsavel",
                        verbose_name="Nome do Responsável",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeto.turma",
                        verbose_name="Turma/Itinerário",
                    ),
                ),
            ],
        ),
    ]
