# Generated by Django 5.1.8 on 2025-04-09 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0002_rename_fist_name_aluno_aluno_first_name_aluno_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="registration_number",
            field=models.CharField(
                default="DEFAULT_REG",
                max_length=20,
                unique=True,
                verbose_name="Número de Registro",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="professor",
            name="disciplina",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Disciplina"
            ),
        ),
        migrations.AddField(
            model_name="professor",
            name="turma",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="professores",
                to="projeto.turma",
                verbose_name="Turma",
            ),
        ),
        migrations.AddField(
            model_name="turma",
            name="padrinho",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="turmas_padrinhadas",
                to="projeto.professor",
                verbose_name="Padrinho",
            ),
        ),
    ]
