# Generated by Django 5.1.8 on 2025-04-09 12:13

import django.db.models.deletion
import projeto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0003_aluno_registration_number_professor_disciplina_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aluno",
            name="first_name_aluno",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="last_name_aluno",
        ),
        migrations.AddField(
            model_name="aluno",
            name="full_name",
            field=models.CharField(
                default="Default Full Name",
                max_length=100,
                verbose_name="Nome Completo",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aluno",
            name="responsavel",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="projeto.responsavel",
                verbose_name="Responsável",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="aluno",
            name="cpf_aluno",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[projeto.models.validate_cpf],
                verbose_name="CPF do aluno",
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="phone_number_aluno",
            field=models.CharField(
                max_length=15,
                validators=[projeto.models.validate_phone],
                verbose_name="Nº do celular (--) ---- ---- do aluno",
            ),
        ),
        migrations.AlterField(
            model_name="responsavel",
            name="cpf",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[projeto.models.validate_cpf],
                verbose_name="CPF do responsável",
            ),
        ),
        migrations.AlterField(
            model_name="responsavel",
            name="phone_number",
            field=models.CharField(
                max_length=15,
                validators=[projeto.models.validate_phone],
                verbose_name="Nº do celular (--) ---- ---- do responsável",
            ),
        ),
    ]
