# Generated by Django 5.1.8 on 2025-04-09 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0005_remove_aluno_id_alter_aluno_registration_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="signed_contract",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="signed_contracts/",
                verbose_name="Contrato Assinado",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="turma",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projeto.turma",
                verbose_name="Turma/Itinerário",
            ),
        ),
    ]
