# Generated by Django 5.1.8 on 2025-04-23 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0006_contrato_signed_contract_alter_contrato_turma"),
    ]

    operations = [
        migrations.AddField(
            model_name="responsavel",
            name="alunos",
            field=models.ManyToManyField(
                related_name="responsaveis",
                to="projeto.aluno",
                verbose_name="Alunos do Responsável",
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="responsavel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Aluno",
                to="projeto.responsavel",
                verbose_name="Responsável",
            ),
        ),
        migrations.CreateModel(
            name="Notas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("materia", models.CharField(max_length=100, verbose_name="Matéria")),
                (
                    "nota_presenca",
                    models.FloatField(
                        default=0, verbose_name="Nota de Presença (Diário)"
                    ),
                ),
                (
                    "nota_atividade",
                    models.FloatField(
                        default=0, verbose_name="Nota de Atividade (Diário)"
                    ),
                ),
                (
                    "nota_avaliativa",
                    models.FloatField(
                        default=0, verbose_name="Nota Avaliativa (Mensal)"
                    ),
                ),
                (
                    "nota_final",
                    models.FloatField(default=0, verbose_name="Nota Final (0 a 100)"),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeto.aluno",
                        verbose_name="Aluno",
                    ),
                ),
            ],
        ),
    ]
