# Generated by Django 5.1.8 on 2025-04-23 11:32

import django.db.models.deletion
import projeto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0007_responsavel_alunos_alter_aluno_responsavel_notas"),
    ]

    operations = [
        migrations.AddField(
            model_name="notas",
            name="turma",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="projeto.turma",
                verbose_name="Turma",
            ),
        ),
        migrations.AlterField(
            model_name="notas",
            name="nota_atividade",
            field=models.FloatField(
                default=0,
                validators=[projeto.models.validate_nota],
                verbose_name="Nota de Atividade (Diário)",
            ),
        ),
        migrations.AlterField(
            model_name="notas",
            name="nota_avaliativa",
            field=models.FloatField(
                default=0,
                validators=[projeto.models.validate_nota],
                verbose_name="Nota Avaliativa (Mensal)",
            ),
        ),
        migrations.AlterField(
            model_name="notas",
            name="nota_final",
            field=models.FloatField(
                editable=False, verbose_name="Nota Final (0 a 100)"
            ),
        ),
        migrations.AlterField(
            model_name="notas",
            name="nota_presenca",
            field=models.FloatField(
                default=0,
                validators=[projeto.models.validate_nota],
                verbose_name="Nota de Presença (Diário)",
            ),
        ),
        migrations.AlterField(
            model_name="responsavel",
            name="alunos",
            field=models.ManyToManyField(
                blank=True,
                related_name="responsaveis",
                to="projeto.aluno",
                verbose_name="Alunos do Responsável",
            ),
        ),
    ]
