# Generated by Django 5.1.8 on 2025-04-23 12:02

import django.db.models.deletion
from django.db import migrations, models

def create_default_materias(apps, schema_editor):
    Materia = apps.get_model('projeto', 'Materia')
    default_materias = [
        Materia(name="Matemática"),
        Materia(name="Português"),
        Materia(name="História"),
        Materia(name="Ciências"),
    ]
    Materia.objects.bulk_create(default_materias)

    # Assign default materias to existing Turma rows
    Turma = apps.get_model('projeto', 'Turma')
    default_materia_ids = list(Materia.objects.values_list('id', flat=True)[:4])
    for turma in Turma.objects.all():
        turma.materia_1_id = default_materia_ids[0]
        turma.materia_2_id = default_materia_ids[1]
        turma.materia_3_id = default_materia_ids[2]
        turma.materia_4_id = default_materia_ids[3]
        turma.save()

class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0008_notas_turma_alter_notas_nota_atividade_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="professor",
            name="disciplina",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="turma",
        ),
        migrations.RemoveField(
            model_name="turma",
            name="itinerario",
        ),
        migrations.AlterField(
            model_name="notas",
            name="turma",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projeto.turma",
                verbose_name="Turma",
            ),
        ),
        migrations.CreateModel(
            name="Materia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome da Matéria"
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materias",
                        to="projeto.professor",
                        verbose_name="Professor Responsável",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="turma",
            name="materia_1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="turma_materia_1",
                to="projeto.materia",
                verbose_name="Matéria 1",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="turma",
            name="materia_2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="turma_materia_2",
                to="projeto.materia",
                verbose_name="Matéria 2",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="turma",
            name="materia_3",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="turma_materia_3",
                to="projeto.materia",
                verbose_name="Matéria 3",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="turma",
            name="materia_4",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="turma_materia_4",
                to="projeto.materia",
                verbose_name="Matéria 4",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notas",
            name="materia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projeto.materia",
                verbose_name="Matéria",
            ),
        ),
        migrations.RunPython(create_default_materias),
    ]
