# Generated by Django 5.1.8 on 2025-04-23 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0009_remove_professor_disciplina_remove_professor_turma_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="turma",
            name="materia_1",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="turma_materia_1",
                to="projeto.materia",
                verbose_name="Matéria 1",
            ),
        ),
        migrations.AlterField(
            model_name="turma",
            name="materia_2",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="turma_materia_2",
                to="projeto.materia",
                verbose_name="Matéria 2",
            ),
        ),
        migrations.AlterField(
            model_name="turma",
            name="materia_3",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="turma_materia_3",
                to="projeto.materia",
                verbose_name="Matéria 3",
            ),
        ),
        migrations.AlterField(
            model_name="turma",
            name="materia_4",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="turma_materia_4",
                to="projeto.materia",
                verbose_name="Matéria 4",
            ),
        ),
    ]
