# Generated by Django 5.1.8 on 2025-04-23 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0010_alter_turma_materia_1_alter_turma_materia_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="professor",
            name="materias",
            field=models.ManyToManyField(
                blank=True,
                related_name="professores_responsaveis",
                to="projeto.materia",
                verbose_name="Matérias",
            ),
        ),
        migrations.AlterField(
            model_name="materia",
            name="professor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="materias_responsaveis",
                to="projeto.professor",
                verbose_name="Professor Responsável",
            ),
        ),
    ]
