# Generated by Django 5.1.8 on 2025-04-23 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0011_professor_materias_alter_materia_professor"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="notas",
            unique_together={("turma", "materia", "aluno")},
        ),
    ]
