# Generated by Django 5.1.8 on 2025-04-23 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0012_alter_notas_unique_together"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Notas",
            new_name="Nota",
        ),
    ]
