# Generated by Django 5.1.8 on 2025-05-14 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0013_rename_notas_nota"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100, verbose_name="Título")),
                ("descricao", models.TextField(verbose_name="Descrição")),
                ("data_evento", models.DateField(verbose_name="Data do Evento")),
                (
                    "arquivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="agenda_files/",
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "lembrete",
                    models.BooleanField(default=False, verbose_name="Lembrete Ativado"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DesempenhoAcademico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bimestre_1",
                    models.FloatField(default=0, verbose_name="Nota 1º Bimestre"),
                ),
                (
                    "bimestre_2",
                    models.FloatField(default=0, verbose_name="Nota 2º Bimestre"),
                ),
                (
                    "bimestre_3",
                    models.FloatField(default=0, verbose_name="Nota 3º Bimestre"),
                ),
                (
                    "bimestre_4",
                    models.FloatField(default=0, verbose_name="Nota 4º Bimestre"),
                ),
                (
                    "media_final",
                    models.FloatField(editable=False, verbose_name="Média Final"),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeto.aluno",
                        verbose_name="Aluno",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeto.materia",
                        verbose_name="Matéria",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeto.turma",
                        verbose_name="Turma",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Livro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=200, verbose_name="Título do Livro"),
                ),
                ("autor", models.CharField(max_length=100, verbose_name="Autor")),
                ("resumo", models.TextField(verbose_name="Resumo")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("disponivel", "Disponível"),
                            ("em_uso", "Em Uso"),
                            ("fora_de_estoque", "Fora de Estoque"),
                            ("indisponivel", "Indisponível"),
                        ],
                        default="disponivel",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "usuario_em_uso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário em Uso",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Presenca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "status",
                    models.CharField(
                        choices=[("F", "Falta"), ("P", "Presente")],
                        max_length=1,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, null=True, verbose_name="Observação"),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeto.aluno",
                        verbose_name="Aluno",
                    ),
                ),
            ],
        ),
    ]
